<a href="https://colab.research.google.com/github/Zheleikina/ML/blob/main/%D0%9C%D0%9D_%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_%D1%82%D0%B0_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук: вектори, матриці та функції

Мета роботи — закріпити навички роботи з **NumPy**: створення та перетворення векторів і матриць, виконання арифметичних і лінійно-алгебраїчних операцій, використання математичних функцій та написання власних функцій.

### Правила виконання
- Виконуйте завдання послідовно.
- Для обчислень використовуйте `numpy`.
- Результати виводьте за допомогою `print()` або просто залишайте змінну останнім рядком комірки.
- Не змінюйте початкові дані, якщо це прямо не зазначено в умові.


## Підготовка

In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)


## Завдання 1. Створення векторів

1. Створіть вектор `a`, що містить числа від 1 до 10.
2. Створіть вектор `b` з 10 рівновіддалених значень від 0 до 1.
3. Виведіть обидва вектори та їх розмір.

In [2]:
# Ваш код тут

a = np.arange(1, 11)
b = np.linspace(0, 1, 10)

print("Вектор a:", a)
print("Вектор b:", b)

print("Розмір a:", a.size)
print("Розмір b:", b.size)

Вектор a: [ 1  2  3  4  5  6  7  8  9 10]
Вектор b: [0.    0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889 1.   ]
Розмір a: 10
Розмір b: 10


## Завдання 2. Арифметичні дії з векторами

Нехай задано:

`x = [2, 4, 6, 8, 10]`  
`y = [1, 3, 5, 7, 9]`

Обчисліть:
- суму `x + y`;
- різницю `x - y`;
- поелементний добуток;
- поелементне ділення;
- квадрат кожного елемента вектора `x`.

In [3]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 3, 5, 7, 9])

# Ваш код тут

print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)
print("x / y =", x / y)
print("x ** 2 =", x ** 2)

x + y = [ 3  7 11 15 19]
x - y = [1 1 1 1 1]
x * y = [ 2 12 30 56 90]
x / y = [2.    1.333 1.2   1.143 1.111]
x ** 2 = [  4  16  36  64 100]


## Завдання 3. Скалярний добуток і норма вектора

Для векторів `u = [3, -1, 2]` та `v = [1, 4, -2]`:

1. Обчисліть скалярний добуток.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами за формулою

\[
\cos(\alpha)=\frac{u\cdot v}{\|u\|\|v\|}
\]


In [4]:
u = np.array([3, -1, 2])
v = np.array([1, 4, -2])

# Ваш код тут

dot_product = u @ v

norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

cos_alpha = dot_product / (norm_u * norm_v)

print("Скалярний добуток:", dot_product)
print("Норма u:", norm_u)
print("Норма v:", norm_v)
print("Косинус кута:", cos_alpha)

Скалярний добуток: -5
Норма u: 3.7416573867739413
Норма v: 4.58257569495584
Косинус кута: -0.2916059217599022


## Завдання 4. Індексація та логічні умови

Створіть вектор із чисел від `-10` до `10`.

За допомогою індексації та логічних масок:
- виберіть усі додатні елементи;
- виберіть усі парні елементи;
- замініть усі від'ємні значення на `0`;
- знайдіть кількість елементів, більших за `5`.

In [5]:
arr = np.arange(-10, 11)

# Ваш код тут

positive = arr[arr > 0]
even = arr[arr % 2 == 0]

arr[arr < 0] = 0

count = np.sum(arr > 5)

print("Додатні елементи:", positive)
print("Парні елементи:", even)
print("Після заміни від'ємних значень на 0:", arr)
print("Кількість елементів, більших за 5:", count)

Додатні елементи: [ 1  2  3  4  5  6  7  8  9 10]
Парні елементи: [-10  -8  -6  -4  -2   0   2   4   6   8  10]
Після заміни від'ємних значень на 0: [ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10]
Кількість елементів, більших за 5: 5


## Завдання 5. Створення матриць

Створіть:

1. Матрицю `A` розміру `3 × 3`, що містить числа від 1 до 9.
2. Нульову матрицю `3 × 4`.
3. Одиничну матрицю `4 × 4`.
4. Матрицю `2 × 5`, заповнену числом `7`.

Виведіть усі матриці.

In [6]:
# Ваш код тут

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

zeros = np.zeros((3, 4))

ones = np.ones((4, 4))

sevens = np.full((2, 5), 7)

print("Матриця A:")
print(A)

print("\nНульова матриця:")
print(zeros)

print("\nОдинична матриця:")
print(ones)

print("\nМатриця, заповнена числом 7:")
print(sevens)

Матриця A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Нульова матриця:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Одинична матриця:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Матриця, заповнена числом 7:
[[7 7 7 7 7]
 [7 7 7 7 7]]


## Завдання 6. Доступ до елементів матриці

Для матриці

\[
M =
\begin{bmatrix}
5 & 2 & 7 & 1\\
3 & 8 & 4 & 6\\
9 & 0 & 2 & 5
\end{bmatrix}
\]

виконайте:
- отримайте другий рядок;
- отримайте третій стовпець;
- отримайте підматрицю з перших двох рядків і останніх двох стовпців;
- знайдіть максимальний і мінімальний елементи.

In [7]:
M = np.array([
    [5, 2, 7, 1],
    [3, 8, 4, 6],
    [9, 0, 2, 5]
])

# Ваш код тут

second_row = M[1]
third_column = M[:, 2]
submatrix = M[:2, -2:]
maximum = M.max()
minimum = M.min()

print("Другий рядок:", second_row)
print("Третій стовпець:", third_column)
print("Підматриця:")
print(submatrix)
print("Максимальний елемент:", maximum)
print("Мінімальний елемент:", minimum)


Другий рядок: [3 8 4 6]
Третій стовпець: [7 4 2]
Підматриця:
[[7 1]
 [4 6]]
Максимальний елемент: 9
Мінімальний елемент: 0


## Завдання 7. Операції з матрицями

Нехай задано дві матриці:

\[
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
B =
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
\]

Обчисліть:
- `A + B`;
- `A - B`;
- поелементний добуток;
- матричний добуток `A @ B`;
- транспоновану матрицю `A`.

In [9]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Ваш код тут

print("A + B:")
print(A + B)

print("\nA - B:")
print(A - B)

print("\nПоелементний добуток:")
print(A * B)

print("\nМатричний добуток A @ B:")
print(A @ B)

print("\nТранспонована матриця A:")
print(A.T)

A + B:
[[ 6  8]
 [10 12]]

A - B:
[[-4 -4]
 [-4 -4]]

Поелементний добуток:
[[ 5 12]
 [21 32]]

Матричний добуток A @ B:
[[19 22]
 [43 50]]

Транспонована матриця A:
[[1 3]
 [2 4]]


## Завдання 8. Визначник та обернена матриця

Для матриці

\[
A =
\begin{bmatrix}
4 & 7\\
2 & 6
\end{bmatrix}
\]

1. Знайдіть визначник.
2. Знайдіть обернену матрицю.
3. Перевірте результат множенням `A @ A_inv`.
4. Поясніть у коментарі, який результат має бути отриманий.

In [10]:
A = np.array([[4, 7],
              [2, 6]])

# Ваш код тут

det_A = np.linalg.det(A)
A_inv = np.linalg.inv(A)

print("Визначник матриці A:", det_A)

print("\nОбернена матриця A:")
print(A_inv)

print("\nПеревірка A @ A_inv:")
print(A @ A_inv)

# Результат множення має бути одиничною матрицею

Визначник матриці A: 10.000000000000002

Обернена матриця A:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка A @ A_inv:
[[ 1. -0.]
 [ 0.  1.]]


## Завдання 9. Розв'язання системи лінійних рівнянь

Розв'яжіть систему:

\[
\begin{cases}
2x + y = 5 \\
x - y = 1
\end{cases}
\]

Подайте коефіцієнти у вигляді матриці `A`, праву частину — вектора `b`, а потім використайте `np.linalg.solve()`.

In [11]:
# Ваш код тут

A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([5, 1])

x = np.linalg.solve(A, b)

print("Матриця A:")
print(A)

print("\nВектор b:")
print(b)

print("\nРозв'язок системи:")
print(x)

Матриця A:
[[ 2  1]
 [ 1 -1]]

Вектор b:
[5 1]

Розв'язок системи:
[2. 1.]


## Завдання 10. Агрегувальні функції

Для матриці

```python
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])
```

знайдіть:
- суму всіх елементів;
- середнє значення;
- середнє по кожному стовпцю;
- суму по кожному рядку;
- стандартне відхилення;
- індекс максимального елемента в кожному рядку.

In [12]:
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32],
    [18, 28, 38]
])

# Ваш код тут

total_sum = data.sum()
mean = data.mean()
column_mean = data.mean(axis=0)
row_sum = data.sum(axis=1)
std = data.std()
max_index = np.argmax(data, axis=1)

print("Сума всіх елементів:", total_sum)
print("Середнє значення:", mean)
print("Середнє по кожному стовпцю:", column_mean)
print("Сума по кожному рядку:", row_sum)
print("Стандартне відхилення:", std)
print("Індекс максимального елемента в кожному рядку:", max_index)

Сума всіх елементів: 285
Середнє значення: 23.75
Середнє по кожному стовпцю: [13.75 23.75 33.75]
Сума по кожному рядку: [60 75 66 84]
Стандартне відхилення: 8.709429755538917
Індекс максимального елемента в кожному рядку: [2 2 2 2]


## Завдання 11. Математичні функції NumPy

Створіть вектор із 9 значень від `-2` до `2`.

Для кожного значення обчисліть:
- квадрат;
- модуль;
- експоненту `e^x`;
- синус;
- косинус.

Окремо створіть вектор із додатних значень і обчисліть для нього натуральний логарифм та квадратний корінь.

In [13]:
x = np.linspace(-2, 2, 9)

# Ваш код тут

square = x ** 2
absolute = np.abs(x)
exponential = np.exp(x)
sinus = np.sin(x)
cosinus = np.cos(x)

positive = x[x > 0]
logarithm = np.log(positive)
square_root = np.sqrt(positive)

print("Вектор x:", x)

print("\nКвадрат:", square)
print("Модуль:", absolute)
print("Експонента e^x:", exponential)
print("Синус:", sinus)
print("Косинус:", cosinus)

print("\nВектор додатних значень:", positive)
print("Натуральний логарифм:", logarithm)
print("Квадратний корінь:", square_root)

Вектор x: [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]

Квадрат: [4.   2.25 1.   0.25 0.   0.25 1.   2.25 4.  ]
Модуль: [2.  1.5 1.  0.5 0.  0.5 1.  1.5 2. ]
Експонента e^x: [0.135 0.223 0.368 0.607 1.    1.649 2.718 4.482 7.389]
Синус: [-0.909 -0.997 -0.841 -0.479  0.     0.479  0.841  0.997  0.909]
Косинус: [-0.416  0.071  0.54   0.878  1.     0.878  0.54   0.071 -0.416]

Вектор додатних значень: [0.5 1.  1.5 2. ]
Натуральний логарифм: [-0.693  0.     0.405  0.693]
Квадратний корінь: [0.707 1.    1.225 1.414]


## Завдання 12. Власна функція

Напишіть функцію `vector_stats(x)`, яка приймає числовий вектор і повертає:

- мінімум;
- максимум;
- середнє;
- медіану;
- стандартне відхилення.

Перевірте функцію на векторі:

`[4, 7, 1, 9, 3, 8, 5]`.

In [14]:
def vector_stats(x):
    # Ваш код тут
    minimum = np.min(x)
    maximum = np.max(x)
    mean = np.mean(x)
    median = np.median(x)
    std = np.std(x)

    return minimum, maximum, mean, median, std


# Перевірка функції
test_vector = np.array([4, 7, 1, 9, 3, 8, 5])

result = vector_stats(test_vector)

print("Мінімум:", result[0])
print("Максимум:", result[1])
print("Середнє:", result[2])
print("Медіана:", result[3])
print("Стандартне відхилення:", result[4])

Мінімум: 1
Максимум: 9
Середнє: 5.285714285714286
Медіана: 5.0
Стандартне відхилення: 2.657296462534039


## Завдання 13. Функція з умовою

Створіть функцію

\[
f(x) =
\begin{cases}
x^2, & x < 0 \\
2x + 1, & x \geq 0
\end{cases}
\]

Застосуйте її до вектора значень від `-5` до `5`.

Спробуйте реалізувати функцію двома способами:
1. через звичайну функцію Python;
2. через `np.where()`.

In [15]:
x = np.arange(-5, 6)

# Варіант 1 — звичайна функція Python
def f(x):
    if x < 0:
        return x ** 2
    else:
        return 2 * x + 1

result_1 = np.array([f(value) for value in x])

print("Варіант 1:")
print(result_1)


# Варіант 2 — np.where()
result_2 = np.where(x < 0, x ** 2, 2 * x + 1)

print("\nВаріант 2:")
print(result_2)

Варіант 1:
[25 16  9  4  1  1  3  5  7  9 11]

Варіант 2:
[25 16  9  4  1  1  3  5  7  9 11]


## Завдання 14. Робота з двовимірною функцією

Нехай

\[
f(x, y) = x^2 + 2y
\]

Задайте:

`x = [1, 2, 3]`  
`y = [10, 20, 30]`

1. Обчисліть значення функції поелементно.
2. Створіть усі можливі комбінації `x` та `y` за допомогою `np.meshgrid()`.
3. Обчисліть `f(x, y)` для кожної комбінації.

In [16]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Ваш код тут

# 1. Поелементне обчислення функції
f_elementwise = x ** 2 + 2 * y

print("Поелементне значення f(x, y):")
print(f_elementwise)

# 2. Усі можливі комбінації x та y
X, Y = np.meshgrid(x, y)

print("\nМатриця X:")
print(X)

print("\nМатриця Y:")
print(Y)

# 3. Обчислення f(x, y) для кожної комбінації
F = X ** 2 + 2 * Y

print("\nЗначення f(x, y) для всіх комбінацій:")
print(F)

Поелементне значення f(x, y):
[21 44 69]

Матриця X:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

Матриця Y:
[[10 10 10]
 [20 20 20]
 [30 30 30]]

Значення f(x, y) для всіх комбінацій:
[[21 24 29]
 [41 44 49]
 [61 64 69]]


## Завдання 15. Підсумкове

Згенеруйте матрицю `5 × 5` із випадкових цілих чисел від `1` до `100`.

Виконайте такі дії:
1. Знайдіть середнє значення кожного рядка.
2. Знайдіть середнє значення кожного стовпця.
3. Замініть усі елементи, менші за загальне середнє матриці, на `0`.
4. Знайдіть рядок із найбільшою сумою.
5. Нормалізуйте початкову матрицю за формулою:

\[
x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}
\]

6. Напишіть функцію, яка виконує таку нормалізацію для довільної числової матриці.

In [17]:
rng = np.random.default_rng(42)
matrix = rng.integers(1, 101, size=(5, 5))

print("Початкова матриця:")
print(matrix)

# Ваш код тут

# 1. Середнє значення кожного рядка
row_mean = matrix.mean(axis=1)
print("\nСереднє значення кожного рядка:")
print(row_mean)

# 2. Середнє значення кожного стовпця
column_mean = matrix.mean(axis=0)
print("\nСереднє значення кожного стовпця:")
print(column_mean)

# 3. Заміна елементів, менших за загальне середнє, на 0
overall_mean = matrix.mean()
matrix_modified = matrix.copy()
matrix_modified[matrix_modified < overall_mean] = 0

print("\nЗагальне середнє:", overall_mean)
print("\nМатриця після заміни:")
print(matrix_modified)

# 4. Рядок із найбільшою сумою
row_sums = matrix_modified.sum(axis=1)
max_row = np.argmax(row_sums)

print("\nСуми рядків:")
print(row_sums)
print("Індекс рядка з найбільшою сумою:", max_row)
print("Рядок із найбільшою сумою:")
print(matrix_modified[max_row])

# 5. Нормалізація початкової матриці
x_min = matrix.min()
x_max = matrix.max()

matrix_norm = (matrix - x_min) / (x_max - x_min)

print("\nНормалізована матриця:")
print(matrix_norm)

# 6. Функція нормалізації довільної матриці
def normalize_matrix(x):
    x_min = x.min()
    x_max = x.max()
    return (x - x_min) / (x_max - x_min)

normalized = normalize_matrix(matrix)

print("\nРезультат роботи функції:")
print(normalized)


Початкова матриця:
[[ 9 78 66 44 44]
 [86  9 70 21 10]
 [53 98 74 77 72]
 [79 52 13 84 46]
 [51 38 19 93 79]]

Середнє значення кожного рядка:
[48.2 39.2 74.8 54.8 56. ]

Середнє значення кожного стовпця:
[55.6 55.  48.4 63.8 50.2]

Загальне середнє: 54.6

Матриця після заміни:
[[ 0 78 66  0  0]
 [86  0 70  0  0]
 [ 0 98 74 77 72]
 [79  0  0 84  0]
 [ 0  0  0 93 79]]

Суми рядків:
[144 156 321 163 172]
Індекс рядка з найбільшою сумою: 2
Рядок із найбільшою сумою:
[ 0 98 74 77 72]

Нормалізована матриця:
[[0.    0.775 0.64  0.393 0.393]
 [0.865 0.    0.685 0.135 0.011]
 [0.494 1.    0.73  0.764 0.708]
 [0.787 0.483 0.045 0.843 0.416]
 [0.472 0.326 0.112 0.944 0.787]]

Результат роботи функції:
[[0.    0.775 0.64  0.393 0.393]
 [0.865 0.    0.685 0.135 0.011]
 [0.494 1.    0.73  0.764 0.708]
 [0.787 0.483 0.045 0.843 0.416]
 [0.472 0.326 0.112 0.944 0.787]]


## Короткий висновок

У 2–3 реченнях напишіть:
- які операції з векторами та матрицями були опрацьовані;
- які функції NumPy виявилися найкориснішими;
- що було найскладнішим у виконанні роботи.


In [ ]:
# За бажанням можна залишити висновок тут як текстовий рядок або коментар

Під час роботи було опрацьовано створення, індексацію та арифметичні операції з векторами й матрицями. Було виконано матричне множення, транспонування, пошук визначника та розв’язання систем рівнянь. Найкориснішими були `np.array()`, `np.mean()`, `np.sum()`, `np.linalg.solve()` та `np.linalg.det()`. Найскладнішими у виконанні роботи були завдання з оберненою матрицею, системою рівнянь та нормалізацією даних.
